### ISSUE TITLE
Show Number of Violations Only for Selected Severity

### ISSUE THREAD

**Issue by SoerenHenning** [ChristianWulf/qa-eclipse-plugin#58]
Currently, the "Number of [PMD|Checkstyle] Violations" is showing the issues of all severity classes - not only of the selected ones. This is somehow confusing. Suggestion: "Number of [PMD|Checkstyle] Violations: 123 (999 in total)"

**Comment by ChristianWulf** [comment]
Done.  Please verify. If ok, please close this issue.

**Comment by SoerenHenning** [comment]
Works as desired, thanks!
