### ISSUE TITLE
Update PMD Version

### ISSUE THREAD

**Issue by SoerenHenning** [ChristianWulf/qa-eclipse-plugin#68]
With PMD 6.0 default sets of rules are organized in "Categories" instead of "Rulesets". When using the current version of the plugin with a configuration for PMD 6, the Eclipse plugin uses all existing rules and not just those that have been listed in the ruleset xml file.

For example, see: https://github.com/cau-se/code-quality-configurations/blob/master/java/pmd.xml

Latest PMD version is 6.7.0

**Comment by ChristianWulf** [comment]
I will have a look at it very soon.

**Comment by Alexander-Krause** [comment]
See #72

**Comment by Alexander-Krause** [comment]
Done with #72
