### ISSUE TITLE
Enable local build withouth upload phase

### ISSUE THREAD

**Issue by Alexander-Krause** [ChristianWulf/qa-eclipse-plugin#69]
The build via `mvn clean package` seems to fail, if you don't comment out [the execution tag in the related pom.xml](https://github.com/ChristianWulf/qa-eclipse-plugin/blob/master/releng/pmd.eclipse.plugin.updatesite/pom.xml).

`[ERROR] Failed to execute goal org.codehaus.mojo:wagon-maven-plugin:1.0-beta-5:upload (upload-repo) on project qa.eclipse.plugin.updatesite: Unable to create a Wagon instance for file:///srv/vhosts/eus/qa/snapshot/: Repository path /srv/vhosts/eus/qa/snapshot does not exist, and cannot be created.`

Is this supposed to happen? Do I miss something here?

**Comment by ChristianWulf** [comment]
I will have a look at it very soon.

**Comment by ChristianWulf** [comment]
Should be solved. Please verify and close this issue afterwards.

**Comment by Alexander-Krause** [comment]
Solved.
